sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.5
      env: guzzle=^5.3.0 monolog=1.10
    - php: 5.5
      env: lowest=true
    - php: 7.0
    - php: 7.0
      env: guzzle=^5.3.0 monolog=1.10
    - php: 7.0
      env: lowest=true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate
  - |
      if [[ $GITHUB_TOKEN ]]; then
        composer config -g github-oauth.github.com "$GITHUB_TOKEN"
      fi
  - |
      if [[ ! $lowest && $guzzle ]]; then
        composer require guzzlehttp/guzzle "$guzzle" --no-update
      fi
  - |
      if [[ ! $lowest && $monolog ]]; then
        composer require monolog/monolog "$monolog" --no-update
      fi

install:
  - |
      if [[ ! $lowest ]]; then
        travis_retry composer install -n -a --prefer-dist
      else
        travis_retry composer update -n -a --prefer-dist --prefer-lowest --prefer-stable
      fi
  - composer info -i -t

script:
  - vendor/bin/phpunit -v

notifications:
  email: false
