language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 5.5
  - 7.0

env:
  - GUZZLE=^5.3.0
  - GUZZLE=^6.1.1
  - PREFER=lowest

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate
  - if [[ -n "$GITHUB_TOKEN" ]]; then composer config -g github-oauth.github.com "$GITHUB_TOKEN"; fi
  - if [[ ! $PREFER ]]; then composer require --no-update guzzlehttp/guzzle "$GUZZLE"; fi

install:
  - if [[ ! $PREFER ]]; then composer install -n -a --prefer-dist; fi
  - if [[ $PREFER = "lowest" ]]; then composer update -n -a --prefer-dist --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit -v
