sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: deps=high
    - php: 5.5
      env: guzzle=^5.3.0 monolog=1.10
    - php: 5.5
      env: deps=low
    - php: 7.0
      env: deps=high
    - php: 7.0
      env: guzzle=^5.3.0 monolog=1.10
    - php: 7.0
      env: deps=low

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate
  - |
      # Configuring composer ...
      if [[ $GITHUB_TOKEN ]]; then
        composer config -g github-oauth.github.com "$GITHUB_TOKEN"
      fi
  - |
      # Preparing Guzzle dependency ...
      if [[ ! $deps && $guzzle ]]; then
        composer require guzzlehttp/guzzle "$guzzle" --no-update
      fi
  - |
      # Preparing Monolog dependency ...
      if [[ ! $deps && $monolog ]]; then
        composer require monolog/monolog "$monolog" --no-update
      fi

install:
  - |
      # Installing dependencies ...
      if [[ $deps = "high" ]]; then
        travis_retry composer update -n -a --prefer-dist
      elif [[ $deps = "low" ]]; then
        travis_retry composer update -n -a --prefer-dist --prefer-lowest
      else
        travis_retry composer install -n -a --prefer-dist
      fi
  - composer info -i

script:
  - vendor/bin/phpunit -v

notifications:
  email: false
