sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.5
      env: deps=low
    - php: 7.0
    - php: 7.0
      env: guzzle=^5.3.0 monolog=1.10
    - php: 7.0
      env: deps=low
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm

before_install:
  - |
      # Disable Xdebug extension ...
      sed -i'' -e 's/^/;/g' ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || true
      php -v | grep -i xdebug || true
  - |
      # Configuring composer ...
      if [[ $GITHUB_TOKEN ]]; then
        composer config -g github-oauth.github.com "$GITHUB_TOKEN"
      fi

      # composer self-update # see https://docs.travis-ci.com/user/languages/php#Installing-Composer-packages
      composer validate
  - |
      # Preparing Guzzle dependency ...
      if [[ ! $deps && $guzzle ]]; then
        composer require guzzlehttp/guzzle "$guzzle" --no-update
      fi
  - |
      # Preparing Monolog dependency ...
      if [[ ! $deps && $monolog ]]; then
        composer require monolog/monolog "$monolog" --no-update
      fi

install:
  - |
      # Installing dependencies ...
      if [[ $deps = "high" ]]; then
        echo "> Installing HIGH deps ..."
        travis_retry composer update -n -o --prefer-dist
      elif [[ $deps = "low" ]]; then
        echo "> Installing LOW deps ..."
        travis_retry composer update -n -o --prefer-dist --prefer-lowest
      else
        echo "> Installing DEFAULT deps ..."
        travis_retry composer install -n -o --prefer-dist
      fi
  - |
      # Listing installed packages ...
      echo "> Composer packages:"
      composer info -i

before_script:
  - |
      # Enable Xdebug extension ...
      sed -i'' -e 's/^;//g' ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || true
      php -v | grep -i xdebug || true

script:
  - vendor/bin/phpunit --coverage-text -v

notifications:
  email: false
