language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - GUZZLE_VERSION=^5.3.0
  - GUZZLE_VERSION=^6.1.1

matrix:
  fast_finish: true

before_install:
  - composer self-update
  - composer require --no-update --dev guzzlehttp/guzzle "$GUZZLE_VERSION"
  - composer validate

install:
  - composer install --no-interaction --prefer-dist --classmap-authoritative

before_script:
  - php -v

script:
  - ./vendor/bin/phpunit --coverage-text -v
