language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 5.5
  - 7.0

env:
  - DEPS=lowest
  - DEPS=highest

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate
  - if [ -n "$GITHUB_TOKEN" ]; then composer config -g github-oauth.github.com "$GITHUB_TOKEN"; fi

install:
  - if [ "$DEPS" = "lowest" ]; then  composer update -n -a --prefer-dist --prefer-lowest; fi
  - if [ "$DEPS" = "highest" ]; then composer update -n -a --prefer-dist; fi

script:
  - vendor/bin/phpunit -v
