language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - dependencies=lowest
  - dependencies=highest

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate
  - [ -n "$GITHUB_OAUTH_TOKEN" ] && composer config -g github-oauth.github.com "$GITHUB_OAUTH_TOKEN" >/dev/null 2>&1

install:
  - [ "$dependencies" = "lowest" ]  && composer update -n -a --prefer-dist --prefer-lowest
  - [ "$dependencies" = "highest" ] && composer update -n -a --prefer-dist

before_script:
  - phpenv config-add xdebug.ini

script:
  - vendor/bin/phpunit --coverage-text -v
