language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 7.0

env:
  - DEPS=lowest
  - DEPS=highest

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate
  - if [ -n "$GITHUB_TOKEN" ]; then composer config -g github-oauth.github.com "$GITHUB_TOKEN"; fi
  - if [ "$DEPS" = "lowest" ];  then export PREFER_LOWEST="--prefer-lowest"; fi
  - if [ "$DEPS" = "highest" ]; then export PREFER_LOWEST=""; fi

install:
  - composer update -n -a --prefer-dist $PREFER_LOWEST

script:
  - vendor/bin/phpunit -v
