language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - dependencies=lowest
  - dependencies=highest

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate
  - if [ -n "$GITHUB_OAUTH_TOKEN" ]; then composer config -g github-oauth.github.com "$GITHUB_OAUTH_TOKEN" >/dev/null 2>&1; fi

install:
  - if [ "$dependencies" = "lowest" ];  then composer update -n -a --prefer-dist --prefer-lowest; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n -a --prefer-dist; fi;

script:
  - ./vendor/bin/phpunit --coverage-text -v
