sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.5
      env: guzzle=^5.3.0 monolog=1.10
    - php: 5.5
      env: deps=lowest
    - php: 7.0
    - php: 7.0
      env: guzzle=^5.3.0 monolog=1.10
    - php: 7.0
      env: deps=lowest

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate
  - |
      if [[ $GITHUB_TOKEN ]]; then
        composer config -g github-oauth.github.com "$GITHUB_TOKEN"
      fi
  - |
      if [[ ! $deps && $guzzle ]]; then
        composer require guzzlehttp/guzzle "$guzzle" --no-update
      fi
  - |
      if [[ ! $deps && $monolog ]]; then
        composer require monolog/monolog "$monolog" --no-update
      fi

install:
  - |
      echo "Installing composer dependencies"
      if [[ $deps = "lowest" ]]; then
        travis_retry composer update -n -a --prefer-dist --prefer-lowest --prefer-stable
      else
        travis_retry composer install -n -a --prefer-dist
      fi
  - composer info -i -t

script:
  - vendor/bin/phpunit -v

notifications:
  email: false
